### ISSUE TITLE
could this dataset applied for x-ray deep denoising？

### ISSUE THREAD

**Issue by Nano-RK** [bmmi/denoising-fluorescence#4]
Mentioned in the article: "This work is dedicated for fluorescence microscopy denoising where the images are corrupted by Poisson-Gaussian noise; in particular,**Poisson noise**, or shot noise, is the dominant noise source"

Due to the lack of dataset in x ray field（not in medical x-ray field），I want use this dataset for training. So could this dataset applied for x-ray deep denoising？the x-ray images are mainly corrupted by poisson noise.

In addition ,the dataset URL cannot be opened in mainland China,

hope for your reply!

**Comment by yzhang34** [comment]
Hello,

If X-ray data are truly Poisson-noise dominated, then I think it is possible to use our dataset for training.

Please consider using VPN to download our dataset.

Thank you!

**Comment by Nano-RK** [comment]
Thank you vary much!

**Comment by Nano-RK** [comment]
> Hello,
> 
> If X-ray data are truly Poisson-noise dominated, then I think it is possible to use our dataset for training.
> 
> Please consider using VPN to download our dataset.
> 
> Thank you!

Thank you vary much!
